// <auto-generated />
using System;
using EfProject;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfProject.Migrations
{
    [DbContext(typeof(EfProjectContext))]
    [Migration("20220812173144_Ignoring unnecesary data")]
    partial class Ignoringunnecesarydata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0-preview.7.22376.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EfProject.Models.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2b8c0bc2-7a2f-49cb-9a0a-66bb407fb17f"),
                            Name = "To-Do"
                        },
                        new
                        {
                            Id = new Guid("8b51488e-c03c-4ea3-b4d2-438f5c01afd1"),
                            Name = "Personal"
                        });
                });

            modelBuilder.Entity("EfProject.Models.Task", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10e7cd7f-e084-4c07-a111-4edab31e494a"),
                            CategoryId = new Guid("2b8c0bc2-7a2f-49cb-9a0a-66bb407fb17f"),
                            CreatedAt = new DateTime(2022, 8, 12, 11, 31, 44, 56, DateTimeKind.Local).AddTicks(7349),
                            Priority = 2,
                            Title = "Bills"
                        },
                        new
                        {
                            Id = new Guid("05f36d64-cf7b-4a51-a38f-4352231abc1b"),
                            CategoryId = new Guid("8b51488e-c03c-4ea3-b4d2-438f5c01afd1"),
                            CreatedAt = new DateTime(2022, 8, 12, 11, 31, 44, 56, DateTimeKind.Local).AddTicks(7361),
                            Priority = 0,
                            Title = "See Movie"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
